<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "muntertheme_contentelements"
 *
 * Auto generated by Extension Builder 2014-08-14
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Munter Theme - Content Elements',
	'description' => 'Additional CEs for Munter Theme',
	'category' => 'misc',
    'version' => '0.0.1',
    'shy' => 1,
	'author' => 'Mario Kehl',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
    'modify_tables' => 'tt_content',
	'clearCacheOnLoad' => 1,
	'version' => '',
	'constraints' => array(
		'depends' => array(
            'typo3' => '6.2.0-6.2.99',
            'muntertheme' => '',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);